AZURE_LOCATION: 'australiaeast'
RESOURCE_NAME_PREFIX: 'apim'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://github.com/JarreNejatyab'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
